spring:
  application:
    name: service-discovery
    
server:
  port: 9181
eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    eureka-server-connect-timeout-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true